### ISSUE TITLE
Cmake builds

### ISSUE THREAD

**Issue by mbillingr** [raviqqe/bdwgc-alloc#1]
Thanks for this crate!

I had to build your crate on a Windows MSVC toolchain. To support this I added optional compilation with Cmake instead of Autotools (this required updating the `bdwgc` and `libatomic_ops` dependencies to the current master branch). 
Cmake builds succeed on Windows and Linux as far I can tell, and they are completely optional. 
You can find my changes [here](https://github.com/mbillingr/bdwgc-alloc/tree/cmake).

Are you interested in a pull request?

Cheers!

**Comment by raviqqe** [comment]
Thanks for reporting that. Your PR would be very helpful as I think I tried to use Cmake on Linux before but I failed for some reason IIRC.
